
spring.application.name=model

# Conexion a base de datos
spring.datasource.url=jdbc:sqlserver://localhost:1332;databaseName=rentamovil;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=queSera!@#12
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Servidor
server.port=8081

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true