export const VEHICLE_STATUS = {
    AVAILABLE: 'DISPONIBLE',
    IN_USE: 'EN_USO',
    RENTED: 'RENTADO',
    MAINTENANCE: 'EN_MANTENIMIENTO',
};

export const VEHICLE_STATUS_LABEL = {
    [VEHICLE_STATUS.AVAILABLE]: 'Disponible',
    [VEHICLE_STATUS.IN_USE]: 'En uso',
    [VEHICLE_STATUS.RENTED]: 'En uso',      
    [VEHICLE_STATUS.MAINTENANCE]: 'Mantenimiento',
};
