export const BankAccountsMock = [
  {
    id: 1,
    bankName: "Bancolombia",
    accountType: "Cuenta de Ahorros",
    accountNumber: "459-002194-12",
    holderName: "RentaMovil S.A.S. — NIT 901.482.109-4",
    qrImageUrl: null,
    isActive: true,
    lastPayment: "Hace 45 min",
    transactions: 142,
  },
  {
    id: 2,
    bankName: "Nequi",
    accountType: "Línea QR Directa",
    accountNumber: "311 456 7890",
    holderName: "RentaMovil S.A.S. — NIT 901.482.109-4",
    qrImageUrl: null,
    isActive: true,
    lastPayment: "Hace 2 horas",
    transactions: 389,
  },
  {
    id: 3,
    bankName: "Davivienda",
    accountType: "Cuenta Corriente",
    accountNumber: "008-992340-91",
    holderName: "RentaMovil S.A.S. — NIT 901.482.109-4",
    qrImageUrl: null,
    isActive: true,
    lastPayment: "Ayer",
    transactions: 84,
  },
  {
    id: 4,
    bankName: "Banco de Bogotá",
    accountType: "Cuenta de Ahorros",
    accountNumber: "102-449102-05",
    holderName: "RentaMovil S.A.S. — NIT 901.482.109-4",
    qrImageUrl: null,
    isActive: false,
    lastPayment: "18 Nov 2023",
    transactions: 51,
  },
];
