import img from "../../../../assets/carro.png";

export const UserMock =
[
  {
    id: "1",
    userName: "Arnoldo",
    name: "Pedro Perez Pena",
    avatar: img,
    email: "pedro@gmail.com",
    phone: "332323232",
    status: "active",
    date: "24/01/2026",
  },
  {
    id: "2",
    userName: "Valentina",
    name: "Valentina Gomez Ruiz",
    avatar: img,
    email: "valentina@gmail.com",
    phone: "3104567890",
    status: "suspende",
    date: "12/01/2021",
  },
  {
    id: "3",
    userName: "CarlosM",
    name: "Carlos Mendoza Ortiz",
    avatar: img,
    email: "carlos@gmail.com",
    phone: "3159876541",
    status: "inactive",
    date: "18/01/2022",
  },
  {
    id: "4",
    userName: "Laura22",
    name: "Laura Martinez Rojas",
    avatar: img,
    email: "laura@gmail.com",
    phone: "3204561237",
    status: "active",
    date: "05/01/2023",
  },
  {
    id: "5",
    userName: "Santiago",
    name: "Santiago Torres Castro",
    avatar: img,
    email: "santiago@gmail.com",
    phone: "3012345678",
    status: "suspended",
    date: "30/09/2021",
  },
  {
    id: "6",
    userName: "CamilaR",
    name: "Camila Ramirez Lopez",
    avatar: img,
    email: "camila@gmail.com",
    phone: "3187654321",
    status: "active",
    date: "16/06/2024",
  },
  {
    id: "7",
    userName: "Andres07",
    name: "Andres Herrera Molina",
    avatar: img,
    email: "andres@gmail.com",
    phone: "3119874563",
    status: "inactive",
    date: "08/12/2020",
  },
  {
    id: "8",
    userName: "Natalia",
    name: "Natalia Cardenas Silva",
    avatar: img,
    email: "natalia@gmail.com",
    phone: "3142589637",
    status: "inactive",
    date: "14/02/2022",
  },
  {
    id: "9",
    userName: "JuanDev",
    name: "Juan Esteban Rodriguez",
    avatar: img,
    email: "juan@gmail.com",
    phone: "3197531598",
    status: "active",
    date: "20/08/2023",
  },
  {
    id: "10",
    userName: "SofiaP",
    name: "Sofia Parra Gonzalez",
    avatar: img,
    email: "sofia@gmail.com",
    phone: "3001234567",
    status: "inactive",
    date: "10/04/2025",
  
}
]