export const UsersMock = [
  {
    id: 1,
    firstName: "Sharik",
    lastName: "Rojas",
    email: "sharik.rojas@rentamovil.com",
    role: "SUPER_ADMIN",
    status: "ACTIVE",
    registeredAt: "12 Ene 2023",
  },
  {
    id: 2,
    firstName: "Carlos",
    lastName: "Mendoza",
    email: "carlos.mendoza@rentamovil.com",
    role: "ADMIN",
    status: "ACTIVE",
    registeredAt: "04 Mar 2023",
  },
  {
    id: 3,
    firstName: "Laura",
    lastName: "Gutierrez",
    email: "laura.gutierrez@rentamovil.com",
    role: "ADMIN",
    status: "ACTIVE",
    registeredAt: "28 Ago 2023",
  },
  {
    id: 4,
    firstName: "Andrés",
    lastName: "Ramírez",
    email: "andres.ramirez@gmail.com",
    role: "CLIENT",
    status: "ACTIVE",
    registeredAt: "19 Jun 2023",
  },
  {
    id: 5,
    firstName: "Valentina",
    lastName: "Torres",
    email: "valentina.torres@gmail.com",
    role: "CLIENT",
    status: "ACTIVE",
    registeredAt: "02 Jul 2023",
  },
  {
    id: 6,
    firstName: "Julián",
    lastName: "Peña",
    email: "julian.pena@gmail.com",
    role: "CLIENT",
    status: "INACTIVE",
    registeredAt: "15 Oct 2023",
  },
  {
    id: 7,
    firstName: "Felipe",
    lastName: "Morales",
    email: "felipe.morales@outlook.com",
    role: "CLIENT",
    status: "BLOCKED",
    registeredAt: "03 Dic 2023",
  },
];
